In [1]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [ ]:
from datetime import date

today = date.today()

#mahasiswa : nama, nim, prodi, mata kuliah, tanggal hari ini, universitas
mahasiswa = ["Putu Akatara Yoga Dhaniswara", 20250070002, "Informatika", "DAA", today, "UPJ"]
print(mahasiswa)

['Putu Akatara Yoga Dhaniswara', 20250070002, 'Informatika', 'DAA', datetime.date(2025, 9, 15), 'UPJ']


In [ ]:
print("NIM", mahasiswa[1])
print("Kampus", mahasiswa[5])

In [10]:
print("Prodi", mahasiswa[2:3])

Prodi ['Informatika']


In [12]:
nested = (100, (200,400,300), 100)
print(nested)

(100, (200, 400, 300), 100)


In [15]:
dictionary = {"Nama" : "Putu Akatara Yoga Dhaniswara", "NIM" : 20250070002, "Prodi" : "Informatika", "Universitas" : "UPJ"}
print(dictionary)

dictionary.get("NIM")

{'Nama': 'Putu Akatara Yoga Dhaniswara', 'NIM': 20250070002, 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


20250070002

In [1]:
bin_colors = ["Red", "Green", "Blue", "Yellow"]
bin_colors[0:2]

['Red', 'Green']

In [2]:
for aColor in bin_colors:
    print(aColor + "Square")

RedSquare
GreenSquare
BlueSquare
YellowSquare


In [5]:
mahasiswa = ["Putu Akatara Yoga Dhaniswara", 20250070002, "Informatika", "DAA", "UPJ"]
print(f"UPJ {mahasiswa}")

UPJ ['Putu Akatara Yoga Dhaniswara', 20250070002, 'Informatika', 'DAA', 'UPJ']


In [6]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
print(UPJ)

('Universitas', 'Pembangunan', 'Jaya')


In [ ]:
data_mahasiswa_prodi = [
    {
        "No": 1,
        "Prodi": "Informatika",
        "Mahasiswa": 50,
        "Laki-laki": 30,
        "Perempuan": 20
    },
    {
        "No": 2,
        "Prodi": "Sistem Informasi",
        "Mahasiswa": 55,
        "Laki-laki": 30,
        "Perempuan": 25
    },
    {
        "No": 3,
        "Prodi": "Teknik Sipil",
        "Mahasiswa": 40,
        "Laki-laki": 30,
        "Perempuan": 10
    }
]

# print seluruh data
print("Data Mahasiswa per Prodi:")
print(data_mahasiswa_prodi)

# Contoh cara mengakses data:
# Mengakses data dari Prodi Informatika (index 0)
prodi_informatika = data_mahasiswa_prodi[0]
print("\nData Prodi Informatika:")
print(f"Jumlah mahasiswa: {prodi_informatika['Mahasiswa']}")
print(f"Jumlah perempuan: {prodi_informatika['Perempuan']}")

# Mengakses data dari Prodi Teknik Sipil (index 2)
prodi_teknik_sipil = data_mahasiswa_prodi[2]
print("\nData Prodi Teknik Sipil:")
print(f"Jumlah laki-laki: {prodi_teknik_sipil['Laki-laki']}")

Data Mahasiswa per Prodi:
[{'No': 1, 'Prodi': 'Informatika', 'Mahasiswa': 50, 'Laki-laki': 30, 'Perempuan': 20}, {'No': 2, 'Prodi': 'Sistem Informasi', 'Mahasiswa': 55, 'Laki-laki': 30, 'Perempuan': 25}, {'No': 3, 'Prodi': 'Teknik Sipil', 'Mahasiswa': 40, 'Laki-laki': 30, 'Perempuan': 10}]

Data Prodi Informatika:
Jumlah mahasiswa: 50
Jumlah perempuan: 20

Data Prodi Teknik Sipil:
Jumlah laki-laki: 30


In [9]:
import numpy as np

A = np.array([[100, 200, 300],
              [700, 600, 500],
              [900, 1000, 800]])

print(A)

AT = A.T

print(AT)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
